// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXCLEnCCPvOCDOnICXRoYqwglK9G16l_I',
    appId: '1:372897383819:android:ed849432b31992d9f11b8e',
    messagingSenderId: '372897383819',
    projectId: 'ecommerce-app-91aed',
    storageBucket: 'ecommerce-app-91aed.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-Bza3IfegxYGY7wR3foXlgIc1U6xRrVI',
    appId: '1:372897383819:ios:98a7b7130236aa76f11b8e',
    messagingSenderId: '372897383819',
    projectId: 'ecommerce-app-91aed',
    storageBucket: 'ecommerce-app-91aed.firebasestorage.app',
    iosBundleId: 'com.example.ecommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBF12WdXKDIquCyzNyVQOB1C5gyP_GoTnQ',
    appId: '1:372897383819:web:4de6a8e07c00c1aaf11b8e',
    messagingSenderId: '372897383819',
    projectId: 'ecommerce-app-91aed',
    authDomain: 'ecommerce-app-91aed.firebaseapp.com',
    storageBucket: 'ecommerce-app-91aed.firebasestorage.app',
    measurementId: 'G-WV9NZPN92Z',
  );
}
